//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetayTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DetayTable()
        {
            this.IlanTable = new HashSet<IlanTable>();
        }
    
        public int DetayId { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
        public string Yil { get; set; }
        public string Renk { get; set; }
        public string Plaka { get; set; }
        public string YakitTuru { get; set; }
        public string Ucret { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IlanTable> IlanTable { get; set; }
    }
}
