//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace arac.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IlanTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IlanTable()
        {
            this.FavoriTable = new HashSet<FavoriTable>();
            this.SiparisTable = new HashSet<SiparisTable>();
        }
    
        public int IlanId { get; set; }
        public string Baslik { get; set; }
        public Nullable<int> KategoriId { get; set; }
        public string AlisTarihi { get; set; }
        public string TeslimTarihi { get; set; }
        public Nullable<int> Kimden { get; set; }
        public string Adres { get; set; }
        public Nullable<int> DetayId { get; set; }
    
        public virtual DetayTable DetayTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<FavoriTable> FavoriTable { get; set; }
        public virtual KategoriTable KategoriTable { get; set; }
        public virtual KullaniciTable KullaniciTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SiparisTable> SiparisTable { get; set; }
    }
}
